name: Check zone file

on: [push, pull_request]

jobs:
  named-checkzone:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run named-checkzone
        uses: grramos/action-named-checkzone@master